// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSLGt-JxigEFxJmZ7Nxp0G2oBjfNdy2rw',
    appId: '1:143456599761:android:8c35fbf5c2ecdcc0d38ff0',
    messagingSenderId: '143456599761',
    projectId: 'cookus-974e6',
    databaseURL: 'https://cookus-974e6-default-rtdb.firebaseio.com',
    storageBucket: 'cookus-974e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKFpsZDPuU4f9aYC8jgrojDzuia8Ezhg8',
    appId: '1:143456599761:ios:f4151443c36e85bdd38ff0',
    messagingSenderId: '143456599761',
    projectId: 'cookus-974e6',
    databaseURL: 'https://cookus-974e6-default-rtdb.firebaseio.com',
    storageBucket: 'cookus-974e6.appspot.com',
    iosClientId: '143456599761-g00p13i5o1jh9s9jj0puk6ghbc4u85fa.apps.googleusercontent.com',
    iosBundleId: 'com.example.aplikasiCookus',
  );
}
